version: '3.7'
services:
  server:
    image: rosenpass
    networks:
      public:
        ipv4_address: 172.31.100.0
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - MODE=server
      - SERVER_PUBLIC_IP=172.31.100.0
      - SERVER_PORT=9999
      - SERVER_VPN_IP=10.11.12.0/24
    volumes:
      - key-directory:/keys

  client1:
    image: rosenpass
    networks:
      public:
        ipv4_address: 172.31.100.1
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - MODE=client
      - SERVER_PUBLIC_IP=172.31.100.0
      - SERVER_PORT=9999
      - CLIENT_VPN_IP=10.11.12.1/24
    volumes:
      - key-directory:/keys

  client2:
    image: rosenpass
    networks:
      public:
        ipv4_address: 172.31.100.2
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - MODE=client
      - SERVER_PUBLIC_IP=172.31.100.0
      - SERVER_PORT=9999
      - CLIENT_VPN_IP=10.11.12.2/24
    volumes:
      - key-directory:/keys

  client3:
    image: rosenpass
    networks:
      public:
        ipv4_address: 172.31.100.3
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - MODE=client
      - SERVER_PUBLIC_IP=172.31.100.0
      - SERVER_PORT=9999
      - CLIENT_VPN_IP=10.11.12.3/24
    volumes:
      - key-directory:/keys

  client4:
    image: rosenpass
    networks:
      public:
        ipv4_address: 172.31.100.4
    cap_add:
      - NET_ADMIN
    privileged: true
    environment:
      - MODE=client
      - SERVER_PUBLIC_IP=172.31.100.0
      - SERVER_PORT=9999
      - CLIENT_VPN_IP=10.11.12.4/24
    volumes:
      - key-directory:/keys

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.100.0/16
        gateway: 172.31.100.10
volumes: 
  key-directory: