version: '3.7'
services:
  server:
    image: rosenpass
    networks:
      rosenpass:
        ipv4_address: 172.26.0.3
        ipv6_address: fe90::3
    cap_add:
      - NET_ADMIN
    privileged: true
    command: 
      - /bin/bash
      - -c
      - |
        echo "reload sysctl"
        sysctl -p
        echo "generate server keys"
        rp genkey server.rosenpass-secret
        rp pubkey server.rosenpass-secret server.rosenpass-public
        echo "copy keys to volume"
        cp -r /server.rosenpass-public /keys
        echo "wait 5 seconds for the keys to be available"
        sleep 5 
        rp exchange server.rosenpass-secret dev rosenpass0 listen 172.26.0.3:9999 peer /keys/client.rosenpass-public allowed-ips fe90::/64 &
        sleep 5
        ip a add fe90::3/64 dev rosenpass0
        sleep 100000
    volumes:
      - ./config/sysctl.conf:/etc/sysctl.conf
      - key-directory:/keys

  client:
    image: rosenpass
    networks:
      rosenpass:
        ipv4_address: 172.26.0.4
        ipv6_address: fe90::4
    cap_add:
      - NET_ADMIN
    privileged: true
    command: 
      - /bin/bash
      - -c
      - |
        echo "reload sysctl"
        sysctl -p
        echo "generate client keys"
        rp genkey client.rosenpass-secret
        rp pubkey client.rosenpass-secret client.rosenpass-public
        echo "copy keys to volume"
        cp -r /client.rosenpass-public /keys
        echo "wait 5 seconds for the keys to be available"
        sleep 5 
        rp exchange client.rosenpass-secret dev rosenpass0 peer /keys/server.rosenpass-public endpoint 172.26.0.3:9999 allowed-ips fe90::/64 &
        sleep 5
        ip a add fe90::4/64 dev rosenpass0
        sleep 10000
    volumes:
      - ./config/sysctl.conf:/etc/sysctl.conf
      - key-directory:/keys
networks:
  rosenpass:
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.26.0.0/16
        gateway: 172.26.0.1
      - subnet: fe90::/64
        gateway: fe90::1
volumes: 
  key-directory: