name: Build the docker image

on: 
    workflow_call:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v22
              with:
                extra_nix_config: |
                  experimental-features = nix-command flakes
              
            # I know this is bad for reproducability, but it is necessary otherwise the pipeline will fail
            # as it does not recognize the relative path correctly, set in the lock file. And i don't want to tamper with the file
            # This should have no effect on reproducability, it is just for the CI to work 
            - name: remove lock
              run: rm flake.lock

            - name: Build flake
              run: nix build .

            - name: Save docker image as a tarball
              run: |
                docker load < result
                docker save -o image.tar rosenpass

            - name: Save docker image in artefactory
              uses: actions/upload-artifact@v3
              with:
                name: rosenpass
                path: image.tar