name: Build 

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The latest version of rosenpass to build from'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Reset input vars
        run: |
          VERSION=$(echo "${{ github.event.inputs.version }}")
          echo "$VERSION" >> $GITHUB_ENV
      - name: TEST
        run: |
          echo "we should build version ${{ github.event.inputs.version }}""