name: Build the docker image

on: 
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install Nix
              uses: cachix/install-nix-action@v22
              with:
                extra_nix_config: |
                  experimental-features = nix-command flakes

            - name: Build flake
              run: nix build .

            - name: Save docker image as a tarball
              run: |
                docker load < result
                docker save -o image.tar rosenpass

            - name: Save docker image in artefactory
              uses: actions/upload-artifact@v3
              with:
                name: rosenpass
                path: image.tar