name: Build and Test

on: 
  pull_request:
    types: [opened]
  workflow_call:
  workflow_dispatch:


jobs:
  build-image:
    uses: ./.github/workflows/build.yaml
    
  test:
    needs: build-image
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set Up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Download docker image
      uses: actions/download-artifact@v3
      with:
        name: rosenpass
        path: .

    - name: Load docker image
      run: docker load -i image.tar

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements.txt

    - name: Run Tests
      run: pytest -s
      working-directory: ./tests
