name: Release Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The latest version of rosenpass to build from'
        required: true
jobs:
  build-and-test-image:
    uses: ./.github/workflows/ci.yaml
  release:
    runs-on: ubuntu-latest
    needs: build-and-test-image

    steps:
      - name: Publish SNAPSHOT
        if: contains(github.ref, 'develop')
        run: |
          PUBLISH_VERSION="${{ github.event.inputs.version }}-SNAPSHOT"
          echo "PUBLISH_VERSION=$PUBLISH_VERSION" >> $GITHUB_ENV
          echo "SNPASHOT version: $PUBLISH_VERSION"

      - name: publish release Version
        if: contains(github.ref, 'main')
        run: |
          PUBLISH_VERSION="${{ github.event.inputs.version }}"
          echo "PUBLISH_VERSION=PUBLISH_VERSION" >> $GITHUB_ENV
          echo "Main version: $PUBLISH_VERSION"


      - name: load the image
        uses: actions/download-artifact@v2
        with:
          name: rosenpass
          path: .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_ACCESS_TOKEN}}

      - name: tag the image
        run: docker tag rosenpass:latest "${{secrets.DOCKER_USERNAME}}/rosenpass:$PUBLISH_VERSION"

      - name: push image to registry
        run: docker push "${{secrets.DOCKER_USERNAME}}/rosenpass:$PUBLISH_VERSION"