name: Build and Test CI

on: 
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install Nix
      uses: cachix/install-nix-action@v13
      with:
        # Enable experimental features for flakes
        extra_nix_config: |
          experimental-features = nix-command flakes
  
    - name: Build flake
      run: nix build .

    - name: Save docker image as a tarball
      run: docker save -o image.tar $(docker load < result)

    - name: Upload docker image
      uses: actions/upload-artifact@v2
      with:
        name: rosenpass
        path: image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download docker image
      uses: actions/download-artifact@v2
      with:
        name: rosenpass
        path: .

    - name: Load docker image
      run: docker load -i image.tar

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements.txt

    - name: Run Tests
      run: |
        cd tests
        pytest -s