name: Build and Test CI

on: 
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Cache Nix Store
      id: cache-nix
      uses: actions/cache@v2
      with:
        path: /nix/store
        key: nix-${{ hashFiles('**/flake.lock') }} 
        # ensure that if a cache miss occurs on the primary key, any previous cache starting with nix- will be used.
        restore-keys: |
          nix-

    - name: Install Nix
      if: steps.cache-nix.outputs.cache-hit != 'true' # Only install Nix if cache wasn't hit
      uses: cachix/install-nix-action@v13
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
  
    - name: Build flake
      run: nix build .

    - name: Save docker image as a tarball
      run: |
        docker load < result
        docker save -o image.tar rosenpass

    - name: Upload docker image
      uses: actions/upload-artifact@v2
      with:
        name: rosenpass
        path: image.tar

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Download docker image
      uses: actions/download-artifact@v2
      with:
        name: rosenpass
        path: .

    - name: Load docker image
      run: docker load -i image.tar

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./tests/requirements.txt

    - name: Run Tests
      run: |
        cd tests
        pytest -s